import matplotlib.pyplot as plt
import numpy as np
from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN, SVMSMOTE, BorderlineSMOTE, KMeansSMOTE
import os
import sys
sys.path.append('./')
from preprocessing_addFeatures import data_preprocessing
from unit.feacture_extractor import extractor
import random

def save_synthetic_sample_plots(x_synthetic, y_synthetic, output_dir="synthetic_data", max_per_label=5, random_state=42):
    """
    Save plots of randomly selected synthetic samples for each unique label.

    Args:
        x_synthetic (np.ndarray): shape (N, D), synthetic samples
        y_synthetic (np.ndarray): shape (N, T), corresponding binary labels
        output_dir (str): folder where plots are saved
        max_per_label (int): maximum number of random samples to save per label
        random_state (int): random seed for reproducibility
    """
    os.makedirs(output_dir, exist_ok=True)
    random.seed(random_state)

    # Group indices by label string
    from collections import defaultdict
    label_to_indices = defaultdict(list)
    for i, label_vec in enumerate(y_synthetic):
        label_str = "_".join(map(str, label_vec))
        label_to_indices[label_str].append(i)

    for label_str, indices in label_to_indices.items():
        selected_indices = random.sample(indices, min(len(indices), max_per_label))
        plt.figure(figsize=(10, 2 * len(selected_indices)))
        for i, idx in enumerate(selected_indices):
            plt.subplot(len(selected_indices), 1, i + 1)
            plt.plot(x_synthetic[idx][:1008])
            # plt.plot(x_synthetic[idx])
            plt.title(f"Synthetic Sample #{idx + 1} - Label: {label_str}")
            plt.xlabel("Time Index")
            plt.ylabel("Signal Value")
            plt.grid(True)
        plt.tight_layout()

        # Save figure
        filename = f"label_{label_str}_random{max_per_label}.png"
        filepath = os.path.join(output_dir, filename)
        plt.savefig(filepath)
        plt.close()

    print(f"Saved random synthetic sample plots by label type to '{output_dir}'")



def oversample_by_label_combination_nonMissing(x_train, y_train, method='SMOTE', random_state=42, k_neighbors=2):
    """
    Apply oversampling to multi-task data by treating each unique label combination as a class,
    excluding samples with a "Missing" pattern (y[:, 0] == 1).

    Returns:
        x_final: np.ndarray - Full training set (original + synthetic + missing)
        y_final: np.ndarray - Corresponding labels
        x_synthetic: np.ndarray - Only synthetic samples generated by oversampler
        y_synthetic: np.ndarray - Corresponding labels for synthetic samples
    """
    # Identify "missing" samples (cannot be oversampled)
    missing_mask = y_train[:, 0] == 1
    non_missing_mask = ~missing_mask

    x_missing = x_train[missing_mask]
    y_missing = y_train[missing_mask]

    x_non_missing = x_train[non_missing_mask]
    y_non_missing = y_train[non_missing_mask]

    # Combine label vectors into integer class labels
    y_combined = np.array([int("".join(map(str, row)), 2) for row in y_non_missing])
    num_tasks = y_train.shape[1]

    # Choose oversampler
    if method == 'SMOTE':
        sampler = SMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'ADASYN':
        sampler = ADASYN(n_neighbors=k_neighbors, random_state=random_state)
    elif method == 'SVMSMOTE':
        sampler = SVMSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'BorderlineSMOTE':
        sampler = BorderlineSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'KMeansSMOTE':
        sampler = KMeansSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    else:
        raise ValueError(f"Unsupported method: {method}")

    # Apply oversampling
    x_resampled, y_combined_resampled = sampler.fit_resample(x_non_missing, y_combined)

    # Determine synthetic samples (those beyond the original count)
    num_original = len(x_non_missing)
    x_synthetic = x_resampled[num_original:]
    y_combined_synthetic = y_combined_resampled[num_original:]

    # Convert integer class labels back to binary label format
    y_resampled = np.array([
        list(map(int, np.binary_repr(label, width=num_tasks)))
        for label in y_combined_resampled
    ])
    y_synthetic = np.array([
        list(map(int, np.binary_repr(label, width=num_tasks)))
        for label in y_combined_synthetic
    ])

    # Combine oversampled data with "missing" samples
    x_final = np.vstack([x_resampled, x_missing])
    y_final = np.vstack([y_resampled, y_missing])

    # Add Features
    x_final = addFeatures(x_final)
    x_synthetic = addFeatures(x_synthetic)

    return x_final, y_final, x_synthetic, y_synthetic

def oversample_by_label_combination(x_train, y_train, method='SMOTE', random_state=42, k_neighbors=2):
    """
    Apply oversampling to multi-task data by treating each unique label combination as a class,
    including samples with a "Missing" pattern (y[:, 0] == 1). For synthetic samples with missing pattern,
    simulate the missingness by zeroing a random interval in the signal.

    Returns:
        x_final: np.ndarray - Full training set (original + synthetic)
        y_final: np.ndarray - Corresponding labels
        x_synthetic: np.ndarray - Only synthetic samples generated by oversampler
        y_synthetic: np.ndarray - Corresponding labels for synthetic samples
    """
    np.random.seed(random_state)

    # Convert label vectors into unique integer classes
    y_combined = np.array([int("".join(map(str, row)), 2) for row in y_train])
    num_tasks = y_train.shape[1]

    # Choose oversampler
    if method == 'SMOTE':
        sampler = SMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'ADASYN':
        sampler = ADASYN(n_neighbors=k_neighbors, random_state=random_state, sampling_strategy = 'minority')
    elif method == 'SVMSMOTE':
        sampler = SVMSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'BorderlineSMOTE':
        sampler = BorderlineSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'KMeansSMOTE':
        sampler = KMeansSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    else:
        raise ValueError(f"Unsupported method: {method}")

    # Apply oversampling to full data
    x_resampled, y_combined_resampled = sampler.fit_resample(x_train, y_combined)

    # Identify synthetic samples
    num_original = len(x_train)
    x_synthetic = x_resampled[num_original:]
    y_combined_synthetic = y_combined_resampled[num_original:]

    # Convert integer class labels back to binary
    y_resampled = np.array([
        list(map(int, np.binary_repr(label, width=num_tasks)))
        for label in y_combined_resampled
    ])
    y_synthetic = np.array([
        list(map(int, np.binary_repr(label, width=num_tasks)))
        for label in y_combined_synthetic
    ])

    # Add artificial missing segments to synthetic samples with missing pattern
    for i in range(len(x_synthetic)):
        if y_synthetic[i][0] == 1:  # If it has a missing pattern
            # Sample length from Gaussian clipped to [20, 504]
            length = int(np.clip(np.random.normal(loc=200, scale=100), 10, 100))
            start = np.random.randint(0, 1008 - length)
            x_synthetic[i, start:start + length] = 0

    # Combine all into final training set
    x_final = x_resampled
    y_final = y_resampled

    # Add Features
    x_final = addFeatures(x_final)
    x_synthetic = addFeatures(x_synthetic)

    return x_final, y_final, x_synthetic, y_synthetic

def addFeatures(x_train):
    x_data = []
    for x in x_train:
        features = extractor(x)
        x_data_num = np.append(x, features)
        x_data.append(x_data_num)
    x_data = np.asarray(x_data).astype(np.float64)
    x_data = np.reshape(x_data, (-1, 1017))
    return x_data

if __name__ == "__main__":
    x_train, y_train, x_val, y_val, _ = data_preprocessing(balanced=False, platform='pytorch', normal_class=False)
    method = 'SMOTE'
    x_final, y_final, x_synthetic, y_synthetic = oversample_by_label_combination(
        x_train[:,:1008], y_train, method=method, random_state=1, k_neighbors=2
    )
    # x_final = addFeatures(x_final)
    # x_synthetic = addFeatures(x_synthetic)
    save_synthetic_sample_plots(
        x_synthetic, y_synthetic,
        output_dir=f"synthetic_data/{method}",
        max_per_label=10,
        random_state=1
    )
