import matplotlib.pyplot as plt
import numpy as np
from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN, SVMSMOTE, BorderlineSMOTE, KMeansSMOTE
import os
from preprocessing_addFeatures import data_preprocessing

def save_synthetic_sample_plots(x_synthetic, y_synthetic, output_dir="synthetic_data", max_plots=100):
    """
    Save plots of synthetic samples with labels in filenames.

    Args:
        x_synthetic (np.ndarray): shape (N, D), synthetic samples
        y_synthetic (np.ndarray): shape (N, T), corresponding binary labels
        output_dir (str): folder where plots are saved
        max_plots (int): maximum number of synthetic samples to save
    """
    os.makedirs(output_dir, exist_ok=True)

    num_samples = min(len(x_synthetic), max_plots)

    for i in range(num_samples):
        plt.figure(figsize=(8, 3))
        plt.plot(x_synthetic[i])
        label_str = "_".join(map(str, y_synthetic[i]))
        plt.title(f"Synthetic Sample #{i+1}\nLabel: {label_str}")
        plt.xlabel("Time Index")
        plt.ylabel("Signal Value")
        plt.grid(True)

        # Save figure
        filename = f"sample_{i+1}_label_{label_str}.png"
        filepath = os.path.join(output_dir, filename)
        plt.savefig(filepath)
        plt.close()

    print(f"Saved {num_samples} synthetic sample plots to '{output_dir}'")

def oversample_by_label_combination(x_train, y_train, method='SMOTE', random_state=42, k_neighbors=2):
    """
    Apply oversampling to multi-task data by treating each unique label combination as a class,
    excluding samples with a "Missing" pattern (y[:, 0] == 1).

    Returns:
        x_final: np.ndarray - Full training set (original + synthetic + missing)
        y_final: np.ndarray - Corresponding labels
        x_synthetic: np.ndarray - Only synthetic samples generated by oversampler
        y_synthetic: np.ndarray - Corresponding labels for synthetic samples
    """
    # Identify "missing" samples (cannot be oversampled)
    missing_mask = y_train[:, 0] == 1
    non_missing_mask = ~missing_mask

    x_missing = x_train[missing_mask]
    y_missing = y_train[missing_mask]

    x_non_missing = x_train[non_missing_mask]
    y_non_missing = y_train[non_missing_mask]

    # Combine label vectors into integer class labels
    y_combined = np.array([int("".join(map(str, row)), 2) for row in y_non_missing])
    num_tasks = y_train.shape[1]

    # Choose oversampler
    if method == 'SMOTE':
        sampler = SMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'ADASYN':
        sampler = ADASYN(n_neighbors=k_neighbors, random_state=random_state)
    elif method == 'SVMSMOTE':
        sampler = SVMSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'BorderlineSMOTE':
        sampler = BorderlineSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    elif method == 'KMeansSMOTE':
        sampler = KMeansSMOTE(k_neighbors=k_neighbors, random_state=random_state)
    else:
        raise ValueError(f"Unsupported method: {method}")

    # Apply oversampling
    x_resampled, y_combined_resampled = sampler.fit_resample(x_non_missing, y_combined)

    # Determine synthetic samples (those beyond the original count)
    num_original = len(x_non_missing)
    x_synthetic = x_resampled[num_original:]
    y_combined_synthetic = y_combined_resampled[num_original:]

    # Convert integer class labels back to binary label format
    y_resampled = np.array([
        list(map(int, np.binary_repr(label, width=num_tasks)))
        for label in y_combined_resampled
    ])
    y_synthetic = np.array([
        list(map(int, np.binary_repr(label, width=num_tasks)))
        for label in y_combined_synthetic
    ])

    # Combine oversampled data with "missing" samples
    x_final = np.vstack([x_resampled, x_missing])
    y_final = np.vstack([y_resampled, y_missing])

    return x_final, y_final, x_synthetic, y_synthetic

if __name__ == "__main__":
    x_train, y_train, x_val, y_val, _ = data_preprocessing(balanced=False, platform='pytorch', normal_class=False)
    x_final, y_final, x_synthetic, y_synthetic = oversample_by_label_combination(x_train, y_train, method='SMOTE', random_state=42, k_neighbors=2)
    save_synthetic_sample_plots(x_synthetic, y_synthetic, output_dir="synthetic_data/SMOTE", max_plots=100)